fix: temporarily disable dd test visibility (#1240)
## Problem
GitHub workflow is failing due to:
```
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
TypeError: Invalid value used in weak set
 ❯ threadHandler .datadog/lib/node_modules/dd-trace/packages/datadog-instrumentations/src/vitest.js:410:19
 ❯ Tinypool.run .datadog/lib/node_modules/dd-trace/packages/datadog-instrumentations/src/vitest.js:429:18
 ❯ runFiles node_modules/vitest/dist/chunks/coverage.DL5VHqXY.js:2793:16
 ❯ Object.runTests node_modules/vitest/dist/chunks/coverage.DL5VHqXY.js:2849:13
 ❯ executeTests node_modules/vitest/dist/chunks/coverage.DL5VHqXY.js:3421:4
 ❯ node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:9638:6
 ❯ Vitest.runFiles node_modules/vitest/dist/chunks/cli-api.BkDphVBG.js:9666:10
```

## Solution
Temporarily disable the datadog test visibility until we can find the
root cause and implement the fix.
Tests still run after disabling the test visibility.